---
driver_plugin: vagrant

platforms:
  - name: ubuntu-16.04
    run_list:
      - 'recipe[apt::default]'
    attributes: { "ssl":{"verify":false} }

  - name: ubuntu-14.04
    run_list:
      - 'recipe[apt::default]'
    attributes: { "ssl":{"verify":false} }

suites:
  - name: install
    run_list:
      - 'recipe[bfd::install]'
  - name: operate
    run_list:
      - 'recipe[bfd::install]'
      - 'recipe[bfd::default]'
  - name: start-beacon
    attributes: {
      "bfd": {
        "service": {
          "control": "--control='127.0.0.1:1001'",
          "listen": "--listen='127.0.0.1'"
        }
      }
    }
    run_list:
      - 'recipe[bfd::install]'
      - 'recipe[bfd::default]'
      - 'recipe[bfd::beacon]'
